name: Build and Publish to DockerHub

on: [push]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - name: Build
      run: |
        docker build -t $DOCKER_HUB_USERNAME/protoc:latest .
    - name: Publish to DockerHub
      run: |
        docker push $DOCKER_HUB_USERNAME/protoc:latest
